### ISSUE TITLE
Compilation command line

### ISSUE THREAD

**Issue by dobodu** [nspsck/RM67162_Micropython_QSPI#3]
Just in order newbies (like me) can compile without getting lost since the latest micropython esp32/boards directory,

Compilation command line should be

`make BOARD_VARIANT=SPIRAM_OCT BOARD=ESP32_GENERIC_S3 USER_C_MODULES=~/RM67162_Micropython_QSPI/micropython.cmake`

**Comment by nspsck** [comment]
You are right, these should be updated! Thank your for point this out!
